Repository threshold-network/token-dashboard, pull requests merged in 2022-08, with the labels that each got.

#151 Update dashboard-ci.yaml with tbtc-v2 packages
  .github/workflows/dashboard-ci.yaml
  .github/workflows/dashboard-mainnet.yml
Labels: :cloud: infrastructure

#158 [Backport] Remove staking bonus banner
  src/components/Modal/StakingBonus/ConnectWallet.tsx
  src/components/Modal/StakingBonus/EligibilityCard.tsx
  src/components/Modal/StakingBonus/EligibilityConfirmation.tsx
  src/components/Modal/StakingBonus/index.tsx
  src/components/StakingBonus/Banner.tsx
  src/components/StakingBonus/Title.tsx
  src/components/StakingBonus/index.ts
  src/enums/modal.ts
  src/pages/Overview/Network/index.tsx
  src/pages/Staking/StakeCard/ProviderAddress.tsx
  src/pages/Staking/index.tsx
  src/types/modal.ts
Labels: :gem: components

#157 Manual approval of deployment to dashboard.test.threshold.network
  .github/actions/build-and-deploy-to-bucket/action.yml
  .github/workflows/dashboard-ci.yml
Labels: :cloud: infrastructure

#166 Update preparation of the artifacts for `solidity-contracts` in `start_dashboard.sh` script
  scripts/start_dashboard.sh
Labels: :scroll: contract integration

#148 Use Countdown hook from components lib
  src/hooks/useCountdown.ts
  src/pages/Staking/RewardsCard.tsx
  src/pages/tBTC/Bridge/components/SweepTimer.tsx
  yarn.lock
Labels: :gem: components

#169 Update validation for min stake
  .env
  src/hooks/useMinStakeAmount.ts
  src/pages/Staking/StakedPortfolioCard.tsx
  src/store/staking/stakingSlice.ts
  src/types/staking.ts
Labels: :gem: components

#156 Multi app staking - authorize applications
  .env
  .env.production
  .github/workflows/dashboard-ci.yml
  src/App.tsx
  src/constants/featureFlags.ts
  src/enums/env.ts
  src/pages/PageLayout.tsx
  src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/AppAuthorizationInfo.tsx
  src/pages/Staking/AuthorizeStakingApps/AuthorizeApplicationsCardCheckbox/index.tsx
  src/pages/Staking/AuthorizeStakingApps/index.tsx
  src/pages/Staking/StakeCard/Header.tsx
  src/pages/Staking/StakeCard/Header/HeaderTitle.tsx
  src/pages/Staking/StakeCard/Header/index.tsx
  src/pages/Staking/StakeCard/StakeAddressInfo/index.tsx
  src/pages/Staking/StakeCard/StakeApplications/AuthorizeApplicationRow.tsx
  src/pages/Staking/StakeCard/StakeApplications/index.tsx
  src/pages/Staking/StakeCard/StakeBalance/LegacyStakeBalances/BalanceTreeItem.tsx
  src/pages/Staking/StakeCard/StakeBalance/LegacyStakeBalances/index.tsx
  src/pages/Staking/StakeCard/StakeBalance/index.tsx
  src/pages/Staking/StakeCard/StakeRewards/index.tsx
  src/pages/Staking/StakeCard/Switcher.tsx
  src/pages/Staking/StakeCard/index.tsx
  src/pages/Staking/StakedPortfolioCard.tsx
  src/pages/Staking/index.tsx
  src/theme/Checkbox.ts
  src/theme/index.ts
  src/types/page.ts
  src/utils/getEnvVariable.ts
  src/utils/percentage.ts
Labels: :gem: components
